services:
    verturin.permmatrix.listener:
        class: verturin\permmatrix\event\main_listener
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '%tables.config%'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    verturin.permmatrix.controller:
        class: verturin\permmatrix\controller\main_controller
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    verturin.permmatrix.user_controller:
        class: verturin\permmatrix\controller\user_controller
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    verturin.permmatrix.edit_controller:
        class: verturin\permmatrix\controller\edit_controller
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@user'
